image: gitpod/workspace-full

# Commands that will run on workspace start
tasks:
  - name: Setup, Install & Build
    init: yarn install
    command: yarn dev

# Ports to expose on workspace startup
ports:
  - port: 3000
    onOpen: open-browser
    name: Website
    description: Website Preview
